Allow the dotfile-submodule-symlinker to check for multiple instances of the system-bash-compat check

diff --git a/bin/dotfiles-submodule-symlinks b/bin/dotfiles-submodule-symlinks
--- a/bin/dotfiles-submodule-symlinks
+++ b/bin/dotfiles-submodule-symlinks
@@ -20,7 +20,12 @@
 # hand does not have a system bash that supports these. It's stuck on an ancient
 # version of bash (v3.2.*). We support this with in-situ swapsies. So just check
 # we're in an environment we expect to be compatible.
-source ./bin/system-bash-compat
+
+# source ./bin/system-bash-compat # << typically how this would be called, but
+#     # << we need to handle this being intended for existing in a submodule.
+#     # << See lower down for how we make sure we find `system-bash-compat`.
+SYSTEM_BASH_COMPAT_BIN=bin/system-bash-compat
+
 # If you need to configure either PROCTOR_OLD_BASH or PROCTOR_BSD_UTIL see the
 # compat script's hook description.
 ################################################################################
@@ -96,6 +101,22 @@ REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
 _PWD="$(pwd)" # ~= "~"
 _SUBMOD="$_PWD/$SUBMOD_PATH" # ~= "~/dotfiles"
 _HOOK_SOURCE="$_PWD/$DSS_HOOKIN_SOURCE"
+
+echo "Looking for a $SYSTEM_BASH_COMPAT_BIN to run the guard..."
+# We needed to know the _SUBMOD path before calling system-bash-compat
+# Favour calling the copy in the submodule state
+if [ -f "$_SUBMOD/$SYSTEM_BASH_COMPAT_BIN" ]; then
+  source $_SUBMOD/$SYSTEM_BASH_COMPAT_BIN
+else
+  # If it doesn't exist in the submodule state, try root repository.
+  if [ -f "$REPO_ROOT/$SYSTEM_BASH_COMPAT_BIN" ]; then
+    source $REPO_ROOT/$SYSTEM_BASH_COMPAT_BIN
+  else
+    # if it was in neither the submod or root, something went wrong
+    echo "Couldn't locate system-bash-compat, is your submodule up to date?"
+    exit 127
+  fi
+fi
 
 echo # Newline
 echo "SUBMODULE PATH IS SET TO $SUBMOD_PATH"
